"""add column to assoc table

Revision ID: 0447645f4343
Revises: 0102435c7c64
Create Date: 2026-02-11 12:10:34.440329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0447645f4343'
down_revision: Union[str, Sequence[str], None] = '0102435c7c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product_association', sa.Column('unit_price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product_association', 'unit_price')
    # ### end Alembic commands ###
